// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Returns Shreyas Gowda's professional profile, contact info, and social links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify(
          {
            name: "Shreyas Gowda",
            role: "Full Stack Developer & UI/UX Designer",
            status: "Fresher, ready to work",
            email: "gowdashreyas136@gmail.com",
            social: {
              instagram: "https://www.instagram.com/_shreyas__.7/",
              github: "https://github.com/shreyas123-g",
              linkedin: "https://www.linkedin.com/in/shreyas-com"
            }
          },
          null,
          2
        )
      }
    ]
  })
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var PROJECTS = [
  { title: "Pizza Website - Figma Design", tech: ["Figma", "UI/UX"], url: "https://www.figma.com/proto/HtiEaxzqk9FSuUIX85gxNG/Untitled" },
  { title: "Cinema TVGo - Streaming Platform", tech: ["Python", "AI/ML"], url: "https://netflix-application-cinema-tvgo.vercel.app/" },
  { title: "AI Weather Forecast App", tech: ["Python", "AI/ML"], url: "https://deployed-weather-eight.vercel.app/" },
  { title: "CineMate - Movie Booking Platform", tech: ["Python", "AI/ML"], url: "https://cinemate-booking01.vercel.app/" },
  { title: "AI Resume Builder", tech: ["Python", "AI/ML"], url: "https://github.com/shreyas123-g/AI-Resume-builder" },
  { title: "Placement Prediction System", tech: ["Python", "AI/ML"], url: "https://github.com/shreyas123-g/placement" },
  { title: "Job Tracker Application", tech: ["Python", "AI/ML"], url: "https://github.com/shreyas123-g/job-tracker" },
  { title: "Car Price Prediction", tech: ["Python", "MongoDB"], url: "https://github.com/shreyas123-g/car-prize-prediction" },
  { title: "Secure Wallet", tech: ["Python", "MongoDB"], url: "https://github.com/shreyas123-g/main-project-of-coin" }
];
var list_projects_default = defineTool2({
  name: "list_projects",
  title: "List portfolio projects",
  description: "Lists Shreyas's featured portfolio projects with tech stack and links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(PROJECTS, null, 2) }],
    structuredContent: { projects: PROJECTS }
  })
});

// src/lib/mcp/tools/list-skills.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var SKILLS = {
  "UI/UX Design": ["Figma", "Graphic Design", "App Design", "Web Design", "Design Systems"],
  "Programming & Development": ["Java", "JavaScript", "HTML", "CSS", "SQL", "Git", "Core Java", "React JS"],
  "Editing": ["Lightroom", "Picsart", "Snapseed", "Photo Editing", "Color Correction"],
  "Other": ["Football", "Volleyball", "Communication", "GitHub", "Teamwork"]
};
var list_skills_default = defineTool3({
  name: "list_skills",
  title: "List skills",
  description: "Returns Shreyas's skills grouped by category.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(SKILLS, null, 2) }],
    structuredContent: { skills: SKILLS }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "shreyas-portfolio-mcp",
  title: "Shreyas Portfolio MCP",
  version: "0.1.0",
  instructions: "Tools for exploring Shreyas Gowda's portfolio: profile/contact, projects, and skills.",
  tools: [get_profile_default, list_projects_default, list_skills_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
